apiVersion: v1
kind: Service
metadata:
  name: todo-list-service
spec:
  type: NodePort
  selector:
    app: todo-list
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
